/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register via phone + password */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login via phone + password */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh and rotate tokens */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["usersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: operations["usersMeUpdate"];
        trace?: never;
    };
    "/api/v1/auth/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send SMS code */
        post: operations["authSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get other user's profile */
        get: operations["usersGetById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload avatar */
        post: operations["usersMeAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List board templates */
        get: operations["boardsTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/standard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get standard Xiangqi board definition */
        get: operations["boardsStandard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create board */
        post: operations["boardsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my boards */
        get: operations["boardsMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{boardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get board detail */
        get: operations["boardsGet"];
        put?: never;
        post?: never;
        /** Delete board */
        delete: operations["boardsDelete"];
        options?: never;
        head?: never;
        /** Update board */
        patch: operations["boardsUpdate"];
        trace?: never;
    };
    "/api/v1/battles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create battle */
        post: operations["battlesCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/battles/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join battle */
        post: operations["battlesJoin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/battles/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quick match */
        post: operations["battlesMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/battles/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Battle history */
        get: operations["battlesHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/battles/{battleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get battle info */
        get: operations["battlesGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my records */
        get: operations["recordsList"];
        put?: never;
        /** Create a record */
        post: operations["recordsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record detail */
        get: operations["recordsGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update record meta */
        patch: operations["recordsUpdate"];
        trace?: never;
    };
    "/api/v1/records/{id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share record */
        post: operations["recordsShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Favorite record */
        post: operations["recordsFavorite"];
        /** Unfavorite record */
        delete: operations["recordsUnfavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments */
        get: operations["recordsCommentsList"];
        put?: never;
        /** Add comment */
        post: operations["recordsCommentsAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export record file */
        get: operations["recordsExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add bookmark/note */
        post: operations["recordsBookmarkAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/bookmarks/{bid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete bookmark/note */
        delete: operations["recordsBookmarkDelete"];
        options?: never;
        head?: never;
        /** Update bookmark/note */
        patch: operations["recordsBookmarkUpdate"];
        trace?: never;
    };
    "/api/v1/records/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record retention preferences */
        get: operations["recordsPrefsGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update record retention preferences */
        patch: operations["recordsPrefsUpdate"];
        trace?: never;
    };
    "/api/v1/community/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Community feed */
        get: operations["communityShares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/shares/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Like a share */
        post: operations["communityLike"];
        /** Unlike a share */
        delete: operations["communityUnlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report content */
        post: operations["communityReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search records */
        get: operations["communitySearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseAuthTokens: {
            /** @example 0 */
            code: number;
            /** @example success */
            message: string;
            data: components["schemas"]["AuthTokens"];
        };
        ApiResponseUser: {
            /** @example 0 */
            code: number;
            /** @example success */
            message: string;
            data: components["schemas"]["User"];
        };
        ApiResponseError: {
            /** @example 1001 */
            code: number;
            /** @example 参数错误 */
            message: string;
            data?: null | {
                details?: string[];
            };
        };
        AuthRegisterRequest: {
            /**
             * @default phone
             * @enum {string}
             */
            type: "phone";
            /** @example 13800000000 */
            phone: string;
            /**
             * @description SMS verification code (optional if disabled)
             * @example 8523
             */
            code?: string;
            /**
             * Format: password
             * @example Abc12345
             */
            password: string;
            /** Format: email */
            email?: string | null;
        };
        AuthLoginRequest: {
            /**
             * @default phone
             * @enum {string}
             */
            type: "phone";
            /** @example 13800000000 */
            phone: string;
            /**
             * Format: password
             * @example Abc12345
             */
            password: string;
        };
        AuthRefreshRequest: {
            /** @example eyJhbGciOi... */
            refreshToken: string;
        };
        AuthTokens: {
            /**
             * @description JWT access token
             * @example eyJhbGciOi...
             */
            accessToken: string;
            /**
             * @description JWT refresh token
             * @example eyJhbGciOi...
             */
            refreshToken: string;
            /**
             * @description Access token TTL in seconds
             * @example 1800
             */
            expiresIn?: number;
        };
        User: {
            /** @example 1024 */
            id?: number;
            /** @example 棋友A */
            nickname?: string;
            /** @example 13800000000 */
            phone?: string;
            avatarUrl?: string | null;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            /** Format: date-time */
            createdAt?: string;
        };
        UserUpdateRequest: {
            nickname?: string;
            /** Format: password */
            password?: string;
            avatarUrl?: string;
        };
        SmsRequest: {
            /** @example 13800000000 */
            phone: string;
        };
        ApiResponseSmsSent: {
            /** @example 0 */
            code: number;
            /** @example 短信已发送 */
            message: string;
            data?: {
                /** @example sms_9f3a2 */
                requestId?: string;
                /** @example 300 */
                expireIn?: number;
            };
        };
        ApiResponseOk: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: Record<string, never> | null;
        };
        Board: {
            /** @example 301 */
            id?: number;
            /** @example 中炮对屏风马 */
            name?: string;
            description?: string | null;
            layout?: {
                pieces?: {
                    /** @example car */
                    type?: string;
                    x?: number;
                    y?: number;
                    /** @enum {string} */
                    side?: "red" | "black";
                }[];
            };
            rules?: components["schemas"]["Rules"];
        };
        BoardTemplate: {
            /** @example 1 */
            id?: number;
            /** @example 中炮对屏风马 */
            name?: string;
            /** @example /img/t1.png */
            preview?: string;
        };
        BoardCreateRequest: {
            name: string;
            description?: string | null;
            layout: Record<string, never>;
            rules?: components["schemas"]["Rules"];
        };
        BoardUpdateRequest: {
            name?: string;
            description?: string | null;
            layout?: Record<string, never>;
            rules?: components["schemas"]["Rules"];
        };
        ApiResponseBoardTemplates: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: components["schemas"]["BoardTemplate"][];
        };
        ApiResponsePageBoardTemplates: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                items?: components["schemas"]["BoardTemplate"][];
                page?: number;
                pageSize?: number;
                total?: number;
            };
        };
        ApiResponseBoardCreateResult: {
            /** @example 0 */
            code?: number;
            /** @example 创建成功 */
            message?: string;
            data?: {
                /** @example 301 */
                boardId?: number;
                name?: string;
            };
        };
        ApiResponsePageBoards: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                items?: components["schemas"]["Board"][];
                page?: number;
                pageSize?: number;
                total?: number;
            };
        };
        ApiResponseBoard: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: components["schemas"]["Board"];
        };
        ApiResponseAvatar: {
            /** @example 0 */
            code?: number;
            /** @example 上传成功 */
            message?: string;
            data?: {
                url?: string;
            };
        };
        Battle: {
            /** @example 501 */
            battleId?: number;
            /** @example waiting */
            status?: string;
            /** @example pvp */
            mode?: string;
            players?: {
                id?: number;
            }[];
            moves?: Record<string, never>[];
        };
        BattleCreateRequest: {
            /** @example pvp */
            mode?: string;
            initialBoardId?: number;
            fogMode?: boolean;
            password?: string | null;
        };
        BattleJoinRequest: {
            battleId: number;
            password?: string | null;
        };
        BattleMatchRequest: {
            /** @example pvp */
            mode?: string;
        };
        BattleHistoryItem: {
            battleId?: number;
            /** @example win */
            result?: string;
        };
        ApiResponseBattleCreateResult: {
            /** @example 0 */
            code?: number;
            /** @example 房间创建成功 */
            message?: string;
            data?: {
                battleId?: number;
                status?: string;
            };
        };
        ApiResponseBattleMatchResult: {
            /** @example 0 */
            code?: number;
            /** @example 匹配成功 */
            message?: string;
            data?: {
                battleId?: number;
            };
        };
        ApiResponseBattle: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: components["schemas"]["Battle"];
        };
        ApiResponsePageBattleHistory: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                items?: components["schemas"]["BattleHistoryItem"][];
                page?: number;
                pageSize?: number;
                total?: number;
            };
        };
        Record: {
            id?: number;
            battleId?: number;
            opponent?: string | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            /** @example red */
            result?: string | null;
            /** @example checkmate */
            endReason?: string | null;
            keyTags?: string[];
            /** @default false */
            favorite: boolean;
            moves?: components["schemas"]["RecordMove"][];
            bookmarks?: components["schemas"]["Bookmark"][];
            /** @default false */
            shared: boolean;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        RecordMove: {
            moveIndex?: number;
            from?: {
                x?: number;
                y?: number;
            };
            to?: {
                x?: number;
                y?: number;
            };
            piece?: {
                type?: string;
                /** @enum {string} */
                side?: "red" | "black";
            };
            capturedType?: string | null;
            capturedSide?: string | null;
            timeSpentMs?: number | null;
        };
        Bookmark: {
            id?: number;
            step?: number;
            label?: string | null;
            note?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        RecordCreateRequest: {
            opponent?: string | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            result?: string | null;
            endReason?: string | null;
            keyTags?: string[];
            moves?: components["schemas"]["RecordMove"][];
            bookmarks?: components["schemas"]["Bookmark"][];
        };
        RecordUpdateRequest: {
            opponent?: string;
            result?: string;
            endReason?: string;
            keyTags?: string[];
        };
        BookmarkCreateRequest: {
            step: number;
            label?: string | null;
            note?: string | null;
        };
        BookmarkUpdateRequest: {
            step?: number;
            label?: string | null;
            note?: string | null;
        };
        ShareRequest: {
            title?: string;
            tags?: string[];
        };
        CommentCreateRequest: {
            /** @example danmu */
            type?: string;
            step?: number;
            content?: string;
        };
        Comment: {
            id?: number;
            type?: string;
            content?: string;
        };
        ApiResponsePageRecords: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                items?: components["schemas"]["Record"][];
                page?: number;
                pageSize?: number;
                total?: number;
            };
        };
        ApiResponseRecord: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: components["schemas"]["Record"];
        };
        ApiResponseBookmarkCreate: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                id?: number;
            };
        };
        ApiResponseShareResult: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                /** @example 9001 */
                shareId?: number;
                /** @example /shares/9001 */
                url?: string | null;
            };
        };
        /** @description 自定义棋局规则（编辑器用），支持模板与图形化自定义 */
        Rules: {
            /** @default 1 */
            ruleVersion: number;
            /** @enum {string} */
            layoutSource: "empty" | "standard" | "template";
            templateRefId?: number | null;
            /**
             * @default relativeToSide
             * @enum {string}
             */
            coordinateSystem: "relativeToSide" | "absolute";
            /**
             * @default analysis
             * @enum {string}
             */
            mode: "analysis" | "localVersus";
            pieceRules: {
                [key: string]: components["schemas"]["PieceRuleConfig"];
            };
            notes?: string | null;
            templatesUsed?: string[];
        };
        PieceRuleConfig: {
            /** @enum {string} */
            ruleType: "template" | "custom";
            templateKey?: string | null;
            movement?: components["schemas"]["MoveSpec"];
            /**
             * @default sameAsMove
             * @enum {string}
             */
            captureMode: "sameAsMove" | "separate";
            capture?: components["schemas"]["MoveSpec"];
            constraints?: components["schemas"]["ConstraintsSpec"];
        };
        MoveSpec: {
            rays?: components["schemas"]["RaySpec"][];
            steps?: components["schemas"]["StepSpec"][];
            gridMask?: number[][];
            maxDestinations?: number;
        };
        RaySpec: {
            directions?: ("N" | "S" | "E" | "W" | "NE" | "NW" | "SE" | "SW")[];
            vectors?: number[][];
            maxSteps?: number | null;
            /** @default 0 */
            requireScreensForMove: number;
            /** @default 0 */
            requireScreensForCapture: number;
            /** @default true */
            stopAtFirstBlocker: boolean;
        };
        StepSpec: {
            offset?: number[];
            requiredEmpty?: number[][];
            /** @default true */
            allowCapture: boolean;
        };
        ConstraintsSpec: {
            /**
             * @default none
             * @enum {string}
             */
            palace: "none" | "insideOnly" | "outsideOnly";
            /**
             * @default none
             * @enum {string}
             */
            river: "none" | "cannotCross" | "mustCross";
            forwardOnlyBeforeRiver?: boolean;
            enableSidewaysAfterRiver?: boolean;
            allowBackwardAfterRiver?: boolean;
        };
        ApiResponseComments: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: components["schemas"]["Comment"][];
        };
        ApiResponseCommentCreate: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                commentId?: number;
            };
        };
        CommunityShareItem: {
            shareId?: number;
            title?: string;
            likes?: number;
        };
        ReportRequest: {
            /** @example share */
            targetType?: string;
            targetId?: number;
            reason?: string;
        };
        ApiResponseReportResult: {
            /** @example 0 */
            code?: number;
            /** @example 已受理 */
            message?: string;
            data?: {
                reportId?: number;
            };
        };
        SearchResultItem: {
            recordId?: number;
            title?: string;
        };
        ApiResponsePageCommunityShares: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                items?: components["schemas"]["CommunityShareItem"][];
                page?: number;
                pageSize?: number;
                total?: number;
            };
        };
        ApiResponsePageSearchResults: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: {
                items?: components["schemas"]["SearchResultItem"][];
                page?: number;
                pageSize?: number;
                total?: number;
            };
        };
        RecordPrefs: {
            /** @example 30 */
            keepLimit?: number;
            /** @example true */
            autoCleanEnabled?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
        RecordPrefsPatch: {
            keepLimit?: number;
            autoCleanEnabled?: boolean;
        };
        ApiResponseRecordPrefs: {
            /** @example 0 */
            code?: number;
            /** @example success */
            message?: string;
            data?: components["schemas"]["RecordPrefs"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokens"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokens"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description Refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokens"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    usersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUser"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    usersMeUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUser"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    authSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmsRequest"];
            };
        };
        responses: {
            /** @description SMS sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSmsSent"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    usersGetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUser"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    usersMeAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 上传头像文件（仅支持 image/png、image/jpeg、image/webp），建议大小 ≤ 2MB
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAvatar"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    boardsTemplates: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageBoardTemplates"];
                };
            };
        };
    };
    boardsStandard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Standard board definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoard"];
                };
            };
        };
    };
    boardsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoardCreateResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    boardsMine: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of boards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageBoards"];
                };
            };
        };
    };
    boardsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoard"];
                };
            };
        };
    };
    boardsDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    boardsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoard"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    battlesCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BattleCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBattleCreateResult"];
                };
            };
        };
    };
    battlesJoin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BattleJoinRequest"];
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBattle"];
                };
            };
        };
    };
    battlesMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BattleMatchRequest"];
            };
        };
        responses: {
            /** @description Matched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBattleMatchResult"];
                };
            };
        };
    };
    battlesHistory: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageBattleHistory"];
                };
            };
        };
    };
    battlesGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                battleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Battle info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBattle"];
                };
            };
        };
    };
    recordsList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                favorite?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Records page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageRecords"];
                };
            };
        };
    };
    recordsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRecord"];
                };
            };
        };
    };
    recordsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRecord"];
                };
            };
        };
    };
    recordsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    recordsShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareRequest"];
            };
        };
        responses: {
            /** @description Shared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseShareResult"];
                };
            };
        };
    };
    recordsFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    recordsUnfavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    recordsCommentsList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseComments"];
                };
            };
        };
    };
    recordsCommentsAdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseCommentCreate"];
                };
            };
        };
    };
    recordsExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binary export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    recordsBookmarkAdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkCreateRequest"];
            };
        };
        responses: {
            /** @description Added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBookmarkCreate"];
                };
            };
        };
    };
    recordsBookmarkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                bid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    recordsBookmarkUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                bid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    recordsPrefsGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prefs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRecordPrefs"];
                };
            };
        };
    };
    recordsPrefsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPrefsPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRecordPrefs"];
                };
            };
        };
    };
    communityShares: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageCommunityShares"];
                };
            };
        };
    };
    communityLike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    communityUnlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOk"];
                };
            };
        };
    };
    communityReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseReportResult"];
                };
            };
        };
    };
    communitySearch: {
        parameters: {
            query?: {
                q?: string;
                tag?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageSearchResults"];
                };
            };
        };
    };
}
