/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register via phone + password */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login via phone + password */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["usersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LEGACY dev - register (no envelope)
         * @description Returns tokens directly { accessToken, refreshToken }.
         */
        post: operations["legacyRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LEGACY dev - login (no envelope)
         * @description Returns tokens directly { accessToken, refreshToken }.
         */
        post: operations["legacyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseAuthTokens: {
            /** @example 0 */
            code: number;
            /** @example success */
            message: string;
            data: components["schemas"]["AuthTokens"];
        };
        ApiResponseUser: {
            /** @example 0 */
            code: number;
            /** @example success */
            message: string;
            data: components["schemas"]["User"];
        };
        ApiResponseError: {
            /** @example 1001 */
            code: number;
            /** @example 参数错误 */
            message: string;
            data?: unknown;
        };
        AuthRegisterRequest: {
            /**
             * @default phone
             * @enum {string}
             */
            type: "phone";
            /** @example 13800000000 */
            phone: string;
            /**
             * @description SMS verification code (optional if disabled)
             * @example 8523
             */
            code?: string;
            /**
             * Format: password
             * @example Abc12345
             */
            password: string;
            /** Format: email */
            email?: string | null;
        };
        AuthLoginRequest: {
            /**
             * @default phone
             * @enum {string}
             */
            type: "phone";
            /** @example 13800000000 */
            phone: string;
            /**
             * Format: password
             * @example Abc12345
             */
            password: string;
        };
        AuthTokens: {
            /**
             * @description JWT access token
             * @example eyJhbGciOi...
             */
            accessToken: string;
            /**
             * @description JWT refresh token
             * @example eyJhbGciOi...
             */
            refreshToken: string;
            /**
             * @description Access token TTL in seconds
             * @example 1800
             */
            expiresIn?: number;
        };
        User: {
            /** @example 1024 */
            id?: number;
            /** @example 棋友A */
            nickname?: string;
            /** @example 13800000000 */
            phone?: string;
            avatarUrl?: string | null;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokens"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokens"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    usersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUser"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseError"];
                };
            };
        };
    };
    legacyRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 13800000000 */
                    phone: string;
                    /**
                     * Format: password
                     * @example Abc12345
                     */
                    password: string;
                    /** @example a@b.com */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
        };
    };
    legacyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 13800000000 */
                    phone: string;
                    /**
                     * Format: password
                     * @example Abc12345
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
        };
    };
}
